# Generated by Django 6.0.2 on 2026-02-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_company'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='suppliers.supplier'),
        ),
    ]
